### PR TITLE
:arrow_up: nan@1.5.1 for iojs support

### PR DESCRIPTION
**Pull request by jonathanong**

### CODE REVIEW

**Comment by chahn** [comment]
:+1:

**Comment by coma** [comment]
:+1:

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by christkv** [comment]
please provide instructions on how to set up a working iojs env so I can test this.currently there seems to be no straight forward way to do this on osx that I can find. I need to test first before accepting the pull request.

**Comment by chahn** [comment]
io.js should soon emerge in homebrew. There's already a PR: https://github.com/Homebrew/homebrew/pull/35853

**Comment by christkv** [comment]
does not solve my node-gyp issues. I need to get to where I can do a node-gyp rebuild

**Comment by jonathanong** [comment]
@christkv if you install iojs, running `npm rebuild` will work. just don't update npm or anything.

**Comment by salzhrani** [comment]
+1

**Comment by chahn** [comment]
Yah. Thanks.

**Comment by nicholaswyoung** [comment]
When can we expect a release of this fix? The sooner it's out, the better for modules that depend on js-bson and their compatibility with io.js.

**Comment by salzhrani** [comment]
Would love a release, please.

**Comment by hectorfhurtado** [comment]
+1

**Comment by christkv** [comment]
it's been out awhile already

**Comment by hectorfhurtado** [comment]
ouch. Since installed io.js I've see this error on my current project

<pre>{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version</pre>

**Comment by ZloyDyadka** [comment]
+

**Comment by jdhiro** [comment]
It looks like there are two issues pointing at each other that are both closed? I'm still getting this with the latest version of everything installed and rebuilt.

**Comment by tiefenb** [comment]
I also still getting this with the latest version and iojs 1.6.x

**Comment by tiefenb** [comment]
I am getting:

[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by christkv** [comment]
if you upgrade your io.js or node version you need to completely flush every npm module as the V8 C++ api's changed making every single native module binary incompatible. It's even worse with io.js as every possible minor upgrade might break.

**Comment by tiefenb** [comment]
thanks, it works now

**Comment by hectorfhurtado** [comment]
HI, I reinstalled every module but I'm still getting this error

<pre>{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version</pre>

I'm on a Windows 7 32bit machine. Running iojs 1.6.2 and mongodb version 2.6.7

**Comment by christkv** [comment]
you need the whole tool chain to build this. Anyway that is a warning not a failure. It falls back to the pure js implementation of the parser. Just ignore it.

**Comment by toni89** [comment]
still getting that message with iojs@2.1.0 and bson@0.3.2 
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: Module did not self-register.]

**Comment by hectorfhurtado** [comment]
Hi, I encountered that I was using an outdated version of mongodb: Ididn't get noticed until I used `npm oudated`, once I changed my package.json and updated, everything runs normal now. Maybe that helps you @toni89

**Comment by toni89** [comment]
@hectorfhurtado thank you, but i have already the newest 2.0.33 version installed. maybe this is an mac os issue!??

**Pull request merged**
