### PR TITLE
use more specific TypeError objects for function parameters errors

### PR DESCRIPTION
**Pull request by hhromic**
Hi,
here is the PR for the proposed changes commented in [here](https://github.com/mongodb/js-bson/issues/156). I went further and modified all other functions in the codebase where this specific error object makes sense (function parameters checking). So the error handling in the lib is consistent.

Cheers and thanks!
Hugo.

### CODE REVIEW

**Comment by mbroadst** [comment]
@hhromic can you please fix the conflicts in this PR so we can merge this? Apologies for taking so longer to get around to this.

**Comment by hhromic** [comment]
no problem @mbroadst !
However, I'm confused on which branch I should send the PR to. In the original discussion we had (#156), it was mentioned that no changes will be accepted until at least version 5.x. However the current default branch is `1.0-branch`.
Can you confirm me to which brand I should rebase the patch for?

**Comment by mbroadst** [comment]
@hhromic yeah I saw that issue as well and was very confused by it. We are currently in the 2.x series, and thats what you should rebase to, the 2.0.0 branch. Thanks!

**Comment by hhromic** [comment]
(closing as new PR is in place now)

**Pull request closed without merging**
