### PR TITLE
Attempting to fix [NODE-1645]

### PR DESCRIPTION
**Pull request by BastienAr**
This tricks seems to fix the [NODE-1645](https://jira.mongodb.org/browse/NODE-1645) issue regarding $ keys. Despite that does not break any test, I really don't feel this is the best way to achieve it. That could be a start to discuss it tho.

### CODE REVIEW

**Comment by devinus** [comment]
I can confirm this issue. We serialize aggregation queries using this library which now fail.

Relevant stacktrace:

```
     Error: key $match must not start with '$'
      at serializeInto (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:912:19)
      at serializeObject (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
      at serializeInto (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:728:17)
      at serializeObject (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
      at serializeInto (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:938:17)
      at serializeObject (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
      at serializeInto (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:728:17)
      at serializeObject (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:348:18)
      at serializeInto (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:938:17)
      at BSON.serialize (node_modules/mongoose/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:63:28)
      at Query.toBin (node_modules/mongoose/node_modules/mongodb-core/lib/connection/commands.js:146:25)
      at serializeCommands (node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1045:43)
      at Pool.write (node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1261:3)
      at executeWrite (node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
      at WireProtocol.insert (node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
      at Server.insert (node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:815:35)
      at Server.insert (node_modules/mongoose/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
      at insertDocuments (node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:822:19)
      at insertOne (node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:852:3)
      at executeOperation (node_modules/mongoose/node_modules/mongodb/lib/utils.js:420:24)
      at Collection.insertOne (node_modules/mongoose/node_modules/mongodb/lib/collection.js:463:10)
      at NativeCollection.(anonymous function) [as insertOne] (node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:143:28)
      at model.Model.$__handleSave (node_modules/mongoose/lib/model.js:183:21)
      at model.Model.$__save (node_modules/mongoose/lib/model.js:252:8)
```

**Comment by kvwalker** [comment]
Thank you for your fix, @BastienAr! I made a slight tweak in https://github.com/mongodb/js-bson/pull/273 that should fix the issue.

**Comment by kvwalker** [comment]
Hi @BastienAr, the driver actually does not support keys with `$` and `.` since the MongoDB server doesn't support querying on such fields. For more context, see [here](https://jira.mongodb.org/browse/JAVA-2810?focusedCommentId=1969488&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1969488). Sorry for the confusion!

**Comment by BastienAr** [comment]
Okay, thanks for pointing me the context. I'm a bit confused and frustrated about the driver being more restrictive than the server tho. I did understand that it's not possible querying on such fields, but some times you just need to store them (this is my use case). Actually mongo itself does it on the _oplog.rs_ [collection](https://docs.mongodb.com/manual/core/replica-set-oplog/) (on update oplogs).

During my debugging, I found that insertOne, insertMany, and others accept the **checkKeys** options. So a workaround could be :

```javascript
client
  .db("db")
  .collection("col")
  .insertOne({ a: { $b: 1 } }, { checkKeys: false })
  .then(console.log);
```

Be extremely careful if you use it, since no check will be done on the request, obviously.

I think the[driver documentation](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#insertOne) should mention the existence of  **checkKeys**  options.

**Comment by daprahamian** [comment]
@BastienAr We have filed [NODE-1652](https://jira.mongodb.org/browse/NODE-1652) to track documenting `checkKeys`

**Pull request closed without merging**
