### PR TITLE
Properly construct new BSONRegExp when constructor called without new

### PR DESCRIPTION
**Pull request by edaniels**

### CODE REVIEW

**Comment by mbroadst** [comment]
@edaniels LGTM, can you please follow this [commit format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits), it helps us automate our changelog generation.

**Comment by edaniels** [comment]
@mbroadst updated

**Comment by mbroadst** [comment]
thanks! will release shortly

**Comment by mbroadst** [comment]
@edaniels 2.0.5 released

**Comment by edaniels** [comment]
@mbroadst thanks! Could you also bump https://github.com/mongodb-js/mongodb-extjson with this version? That's the one the Stitch JS SDK depends on.

**Comment by mbroadst** [comment]
yep, presently doing just that 👍

**Pull request merged**
