### PR TITLE
Fixed browser property in package.json

### PR DESCRIPTION
**Pull request by aydrian**
Updated the `webpack.dist.config.js` to make `npm run build` work.
Updated the `browser` property in `package.json` to point to the webpack output.
Added a `prepublishOnly` script to ensure the transpiled version is built.

### CODE REVIEW

**Comment by hswolff** [comment]
It may be additionally desired to gitignore the `browser_build` folder as that seems un-necessary. Can just be included in the npm package.

**Comment by aydrian** [comment]
@daprahamian Would you like me to add that to the `.gitignore` while I have this open?

**Comment by daprahamian** [comment]
@aydrian Yeah, that would be great, thanks!

**Comment by aydrian** [comment]
@daprahamian No problem. Good to go.

**Pull request merged**
